webtalk_init -webtalk_dir C:/Users/Jonemaster/Desktop/Cihlab/Problem1/Vivado/4bit_counter/4bit_counter.sim/sim_1/behav/xsim/xsim.dir/counter_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat May  3 22:53:47 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b13bf83b-2aa4-4dd1-83a6-411c4b2a6a09" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "735deb928509448187c8af3bda3d0278" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "31" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 7840HS w/ Radeon 780M Graphics     " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3793 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "59.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "9532_KB" -context "xsim\\usage"
webtalk_transmit -clientid 438530383 -regid "" -xml C:/Users/Jonemaster/Desktop/Cihlab/Problem1/Vivado/4bit_counter/4bit_counter.sim/sim_1/behav/xsim/xsim.dir/counter_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Jonemaster/Desktop/Cihlab/Problem1/Vivado/4bit_counter/4bit_counter.sim/sim_1/behav/xsim/xsim.dir/counter_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Jonemaster/Desktop/Cihlab/Problem1/Vivado/4bit_counter/4bit_counter.sim/sim_1/behav/xsim/xsim.dir/counter_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
